# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Cpp_rowSums <- function(x) {
    .Call(`_omicsRWR_Cpp_rowSums`, x)
}

Cpp_colSums <- function(x) {
    .Call(`_omicsRWR_Cpp_colSums`, x)
}

Arma_Inv <- function(x) {
    .Call(`_omicsRWR_Arma_Inv`, x)
}

rwr_cpp <- function(adj_mat, init_scores, int_scores = NULL, restart_prop = 0.15, num_iter = 1000L, delta = 1e-6) {
    .Call(`_omicsRWR_rwr_cpp`, adj_mat, init_scores, int_scores, restart_prop, num_iter, delta)
}

